"""Generate the SVG hero graphics used in the design previews.

The figure is a heavy-tailed dispersal kernel: many short displacements and a
few very long ones, drawn as trajectories radiating from a ringing site. This
is the empirical pattern reported in Fandos et al. (2023, J. Anim. Ecol.), so
the site's main visual element encodes the research rather than decorating it.

Seeded for reproducibility. Run: python3 design/generate_kernel.py
"""

import math
import random

SEED = 20261052
W, H = 1200, 700
# The ringing site sits low in the gap between the hero text and the portrait
# (viewBox coordinates; the SVG is sliced to the hero at xMidYMid). The fan
# leans up and to the right, over the top of the portrait and into the right
# margin, so the traces stay off the running text (design/BRIEF.md section 3).
# The seed was chosen so that the ochre arrival nodes land in the open areas of
# the hero at desktop widths: check with design/tools/snap.sh after changing it.
ORIGIN = (680, 575)
# Geometry: heavy-tailed log-normal distances, with the tail compressed above
# TAIL_KNEE so the longest events still terminate inside the viewBox. The
# class/opacity of each trace is taken from the raw distance, so what counts
# as "long distance" does not depend on the compression.
TAIL_KNEE, TAIL_K = 280, 90
ANGLES = (-112, -15)   # degrees; upward, leaning right


def compress(dist):
    """Log-compress distances above TAIL_KNEE (identity below it)."""
    if dist <= TAIL_KNEE:
        return dist
    return TAIL_KNEE + TAIL_K * math.log1p((dist - TAIL_KNEE) / TAIL_K)


def kernel_paths(n=90, seed=SEED):
    """Trajectories with log-normal step lengths (heavy right tail)."""
    rng = random.Random(seed)
    paths = []
    for _ in range(n):
        # log-normal distance: median ~modest, occasional long-distance events
        dist = rng.lognormvariate(mu=5.0, sigma=0.95)
        dist = min(dist, 1500)
        angle = math.radians(rng.uniform(*ANGLES))
        bow_frac = rng.uniform(-0.28, 0.28)
        drawn = compress(dist)
        x2 = ORIGIN[0] + drawn * math.cos(angle)
        y2 = ORIGIN[1] + drawn * math.sin(angle)
        # control point offset perpendicular to the chord -> gentle arcs
        mx, my = (ORIGIN[0] + x2) / 2, (ORIGIN[1] + y2) / 2
        dx, dy = x2 - ORIGIN[0], y2 - ORIGIN[1]
        norm = math.hypot(dx, dy) or 1
        bow = bow_frac * norm
        cx, cy = mx - dy / norm * bow, my + dx / norm * bow
        paths.append((dist, f"M{ORIGIN[0]:.0f},{ORIGIN[1]:.0f} Q{cx:.1f},{cy:.1f} {x2:.1f},{y2:.1f}"))
    paths.sort(key=lambda p: p[0])
    return paths


def svg(theme):
    """theme: 'dark' or 'light'."""
    paths = kernel_paths()
    longest = max(d for d, _ in paths)
    out = [
        f'<svg class="kernel" viewBox="0 0 {W} {H}" preserveAspectRatio="xMidYMid slice" '
        f'aria-hidden="true" focusable="false">'
    ]
    for i, (dist, d) in enumerate(paths):
        t = dist / longest              # 0 = short hop, 1 = longest movement
        width = 0.6 + 2.1 * t
        op = (0.12 + 0.58 * t) if theme == "dark" else (0.18 + 0.56 * t)
        cls = "trace long" if t > 0.55 else "trace"
        dash = 2200
        delay = i * 0.028
        out.append(
            f'<path class="{cls}" d="{d}" stroke-width="{width:.2f}" '
            f'style="opacity:{op:.3f};stroke-dasharray:{dash};stroke-dashoffset:{dash};'
            f'animation-delay:{delay:.2f}s"/>'
        )
        if t > 0.62:  # mark the arrival point of long-distance events
            end = d.split()[-1]
            ex, ey = end.split(",")
            out.append(f'<circle class="node" cx="{ex}" cy="{ey}" r="{2.2 + 2 * t:.1f}"/>')
    out.append(f'<circle class="origin" cx="{ORIGIN[0]}" cy="{ORIGIN[1]}" r="5"/>')
    out.append("</svg>")
    return "\n".join(out)


# CSS for the standalone file. In the site the same rules live in
# styles/lattice.scss (under .hero .kernel), driven by the theme tokens.
STANDALONE_CSS = """
.trace{fill:none;stroke:#0f5f58;stroke-linecap:round;animation:draw 2.6s cubic-bezier(.2,.7,.25,1) both}
.trace.long{stroke:#b87309}
.node{fill:#b87309;opacity:.72}
.origin{fill:#0f1e26}
@keyframes draw{to{stroke-dashoffset:0}}
@media (prefers-reduced-motion:reduce){.trace{animation:none;stroke-dashoffset:0!important}}
"""


if __name__ == "__main__":
    import pathlib
    here = pathlib.Path(__file__).parent
    root = here.parent
    (here / "kernel-dark.svg.part").write_text(svg("dark"))
    (here / "kernel-light.svg.part").write_text(svg("light"))
    print("wrote kernel-dark.svg.part and kernel-light.svg.part")

    # Quarto include for the home page hero (styled by styles/lattice.scss).
    light = svg("light")
    inc = root / "_includes" / "hero-kernel.qmd"
    inc.parent.mkdir(exist_ok=True)
    inc.write_text(
        "<!-- Generated by design/generate_kernel.py. Do not edit by hand:\n"
        "     run `python3 design/generate_kernel.py` to regenerate.\n"
        "     90 simulated trajectories from one ringing site, log-normal\n"
        "     distances (tail compressed to fit the frame), seeded. -->\n"
        "```{=html}\n" + light + "\n```\n"
    )
    print(f"wrote {inc.relative_to(root)}")

    # Standalone SVG (own CSS, xmlns) for reuse outside the site.
    out = root / "images" / "hero" / "kernel-light.svg"
    out.parent.mkdir(parents=True, exist_ok=True)
    standalone = light.replace(
        '<svg class="kernel"', '<svg xmlns="http://www.w3.org/2000/svg" class="kernel"', 1
    ).replace(">", f"><style>{STANDALONE_CSS}</style>", 1)
    out.write_text(standalone)
    print(f"wrote {out.relative_to(root)}")
